# lib/tasks/compliance.rake
#
# Phase 7 — evidence automation. `compliance:evidence` is the reproducible "where's the proof for
# control X" run: it invokes the existing READ-ONLY verifiers/reporters and captures each one's
# output + result into a timestamped bundle under tmp/evidence/<ts>/, with an INDEX.md summary.
#
# READ-ONLY by construction — it only runs verify/report/smoke tasks and a dependency audit; it never
# touches the destructive backfill/purge/scrub paths (those stay operator-run with CONFIRM=1). Each
# rake verifier runs IN-PROCESS with its stdout/stderr captured and its `abort` (SystemExit) rescued,
# so a single FAIL is recorded rather than killing the whole bundle; the aggregator exits non-zero at
# the end iff a GATING check failed, so it doubles as a pre-deploy gate.
#
# NB on in-process (not shelling `bundle exec`): the dev/prod image sets BUNDLE_PATH=/usr/local/bundle
# via ENV, and shelling a nested `bundle exec` from inside this bundler process fails to resolve gems
# (Bundler.with_unbundled_env strips BUNDLE_PATH). Invoking the tasks in-process avoids that entirely.
# bundle-audit is a standalone bin that reads Gemfile.lock directly, so it needs no `bundle exec`.
#
# Evidence pointers: this is the runnable index behind ssp.md §6 and control-matrix.md CC4.

namespace :compliance do
  # Rake verifiers invoked in-process. [display name, task name, gating?]
  EVIDENCE_TASKS = [
    ['encryption_verify',               'encryption:verify',               true],
    ['history_verify_versions',         'history:verify_versions',         true],
    ['history_verify_client_histories', 'history:verify_client_histories', true],
    ['break_glass_smoke',               'break_glass:smoke',               true],
    ['retention_report',                'retention:report',                false], # read-only snapshot, informational
    # POAM-015: gating, but an EMPTY manifest passes (nothing archived yet is a valid state on a
    # fresh install); only a checksum/count mismatch fails.
    ['retention_verify_archive',        'retention:verify_archive',        true]
  ].freeze

  desc 'Run the read-only compliance verifiers into a timestamped evidence bundle (tmp/evidence/<ts>/). ' \
       'Exits non-zero if any GATING check fails; doubles as a pre-deploy gate.'
  task evidence: :environment do
    require 'fileutils'
    require 'stringio'
    ts  = ENV['TS'].presence || Time.now.utc.strftime('%Y%m%dT%H%M%SZ')
    dir = Rails.root.join('tmp', 'evidence', ts)
    FileUtils.mkdir_p(dir)
    puts "[compliance:evidence] bundle => #{dir}"

    results = []

    EVIDENCE_TASKS.each do |name, task_name, gating|
      out = StringIO.new
      status = 0
      orig_out, orig_err = $stdout, $stderr
      begin
        $stdout = out; $stderr = out
        Rake::Task[task_name].reenable
        Rake::Task[task_name].invoke
      rescue SystemExit => e            # a verifier called abort/exit on failure
        status = e.status.to_i
        status = 1 if status.zero?
      rescue StandardError => e
        out.puts "#{e.class}: #{e.message}"
        status = 1
      ensure
        $stdout = orig_out; $stderr = orig_err
      end
      File.write(dir.join("#{name}.txt"), "# rake #{task_name}\n(exit #{status})\n\n#{out.string}")
      results << record(name, task_name, gating, status)
    end

    # bundle-audit: standalone bin (reads Gemfile.lock; no `bundle exec` / no app bundle needed).
    ba = `bundle-audit check --update 2>&1`
    ba_status = $?.exitstatus
    File.write(dir.join('bundle_audit.txt'), "$ bundle-audit check --update\n(exit #{ba_status})\n\n#{ba}")
    results << record('bundle_audit', 'bundle-audit check --update', true, ba_status)

    File.write(dir.join('INDEX.md'), index_md(ts, results))

    results.each do |r|
      label = r[:pass] ? 'PASS' : (r[:gating] ? 'FAIL' : 'INFO')
      puts format('  %-34s %-4s (exit %d)', r[:name], label, r[:status])
    end

    failed = results.select { |r| r[:gating] && !r[:pass] }
    if failed.any?
      abort "[compliance:evidence] FAIL — gating checks failed: #{failed.map { |r| r[:name] }.join(', ')} (see #{dir})"
    end
    puts "[compliance:evidence] ALL GATING CHECKS PASS (#{dir})"
  end

  def self.record(name, cmd, gating, status)
    { name: name, cmd: cmd, gating: gating, status: status, pass: status.zero? }
  end

  def self.index_md(ts, results)
    md = +"# Compliance evidence bundle — #{ts}\n\n"
    md << "Generated by `rake compliance:evidence` (read-only). Companion to `docs/compliance/ssp.md` §6.\n\n"
    md << "| Check | Gating | Exit | Result |\n|---|---|---|---|\n"
    results.each do |r|
      result = r[:pass] ? 'PASS' : (r[:gating] ? 'FAIL' : 'info')
      md << "| `#{r[:name]}` | #{r[:gating] ? 'yes' : 'no'} | #{r[:status]} | #{result} |\n"
    end
    md << "\nEach `<check>.txt` holds the command, exit code, and full output.\n"
    md
  end
end
